# config file for ginserver

RunMode: debug # gin.ginMode [debug, test, release]
AppName: ginserver
StaticDir: web/static
TemplateDir: web/template
CasbinModelFile: configs/rbac_model.conf # casbin policy config

HttpServer:
  IP:
  Port: 8080
  ReadTimeout: 10 # second
  WriteTimeout: 10 # second
  IdleTimeout: 20
  MaxConnsPerHost: 1000
  MaxIdleConns: 100
  MaxIdleConnsPerHost: 10
  MaxHeaderBytes: 4096

Fix:
  TimeZone:
    Name: UTC
    Offset: 8 # hour

Log: # zerolog
  RecordFile: true
  FileName: ./logs/httpserver_%Y_%m_%d_%H.log
  LinkName: ./logs/httpserver.log
  RotateHour: 1
  ReportCaller: true # write log with runtime file and func
  Level: -1 # [7:Disabled, 6:NoLevel, 5:panic, 4:fatal, 3:error, 2:warn, 1:info, 0:debug, -1:trace]
  TimeLayout: 2006/01/02 15:04:05.000000

DataBase: # xorm
  - DriverName: mysql
    DataBase: ginserver
    Host: 127.0.0.1
    Port: 3306
    Username: ginserver
    Password: 123456
    Charset: utf8mb4
    LogLevel: 0 # [0:LOG_DEBUG, 1:LOG_INFO, 2:LOG_WARNING, 3:LOG_ERR, 4:LOG_OFF, 5:LOG_UNKNOWN]
    ConnMaxLifetime: 60 # minute
    MaxIdleConns: 100
    MaxOpenConns: 100
    ShowSql: true
    ShowExecTime: true
    Connect: true # need to connect database when server start?

Session: # Provider support [memstore, redis], you can use other types by site support [https://github.com/gin-contrib/sessions]
  Provider: memstore # if you chose [redis], you must set Redis connect information
  Path: ginserver
  Domain: 127.0.0.1:3306
  Secret: ginserver
  MaxAge: 7200 # second
  HttpOnly: true
  RedisPassword:

Redis:
  - Host: 127.0.0.1
    Port: 6379
    Password:

Lang:
  Default: zh-CN
  Lang: [en-US, zh-CN]